openapi: 3.0.0

info:
  title: Book Management
  description: The Book Management REST-based API supports book management of an online library. The API includes the following capabilities and operations...
  contact: {}
  version: '1.0.0'
servers:
  - url: 'http://localhost:5000'
    description: 'Local development server'
  - url: 'http://38.29.145.35:40944'
    description: 'Cloud deployment server'
  - url: 'https://2526-ii-int-3505-1-neon.vercel.app/'
    description: 'Vercel deployment server'

paths:
  /books:
    get:
      tags: 
       - Books
      summary: Return a list of books
      description: Provides a list of books based on the search criteria provided...
      operationId: ListBooks
      parameters:
       - name: title
         in: query
         required: false
         description: A query string use for filtering books by title. If not provided, all book will be listed.
         schema: 
          type: string
      responses:
        '200':
          description: Success
          content: 
            application/json:
              schema: 
                  $ref: '#/components/schemas/ListBookResponse'
        '401': 
          description: Request failed. Invalid credentials.
        '403':
          description: Request failed. Unauthorized access.
    post:
      tags:
        - Books
      summary: Create a new book
      description: Create a new book in the library system.
      operationId: CreateBook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBookRequest'
      responses:
        '201':
          description: Book created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookDetails'
        '400':
          description: Invalid request data
        '401':
          description: Request failed. Invalid credentials.
        '403':
          description: Request failed. Unauthorized access.
  
  /books/{bookId}:
    get:
      tags:
        - Books
      summary: Get Book by ID
      description: Retrieve a specific book using its identifier
      operationId: GetBookById
      parameters:
        - name: bookId
          in: path
          required: true
          description: The unique identifier of a book
          schema:
            type: string
      responses:
        '200':
          description: Book Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookDetails'
        '401':
          description: Request failed. Invalid credentials.
        '403':
          description: Request failed. Unauthorized access.
        '404':
          description: Request failed. Book not found.
    
    put:
      tags:
        - Books
      summary: Update book by ID
      description: Update the details of an existing book using its ID.
      operationId: UpdateBook
      parameters:
        - name: bookId
          in: path
          required: true
          description: The unique identifier of the book
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBookRequest'
      responses:
        '200':
          description: Book updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookDetails'
        '400':
          description: Invalid request data
        '404':
          description: Book not found
        '401':
          description: Request failed. Invalid credentials.
        '403':
          description: Request failed. Unauthorized access.
      
    patch:
      tags:
        - Books
      summary: Partially update book by ID
      description: Partially update the details of an existing book using its ID.
      operationId: PatchBook
      parameters:
        - name: bookId
          in: path
          required: true
          description: The unique identifier of the book
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateBookRequest'
      responses:
        '200':
          description: Book updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookDetails'
        '400':
          description: Invalid request data
        '404':
          description: Book not found
        '401':
          description: Request failed. Invalid credentials.
        '403':
          description: Request failed. Unauthorized access.

    delete:
      tags:
        - Books
      summary: Delete book by ID
      description: Delete existing book using its identifier.
      operationId: DeleteBook
      parameters:
        - name: bookId
          in: path
          required: true
          description: The unique identifier of the book
          schema: 
            type: string
      responses:
        '200':
          description: Book deleted successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookDetails'
        '404':
          description: Book not found
        '401':
          description: Request failed. Invalid credentials.
        '403':
          description: Request failed. Unauthorized access.

components:
  schemas:
    ListBookResponse: 
      title: ListBookResponse
      type: object
      properties:
        books:
          type: array
          description: A list of book details
          items: 
            $ref: '#/components/schemas/BookDetails'
    BookDetails:
      title: BookDetails
      type: object
      properties:
        bookId:
          type: string
          description: An identifier of book
        title:
          type: string
          description: The title of book
        author:
          type: string
          description: The author of the book
        publishYear:
          type: integer
          description: The year the book was published
    CreateBookRequest:
      title: CreateBookRequest
      type: object
      required:
        - title
        - author
        - publishYear
      properties:
        title:
          type: string
          description: The title of the book
        author:
          type: string
          description: The author of the book
        publishYear:
          type: integer
          description: The year the book was published
    UpdateBookRequest:
      title: UpdateBookRequest
      type: object
      properties:
        title:
          type: string
          description: The title of the book
        author:
          type: string
          description: The author of the book
        publishYear:
          type: integer
          description: The year the book was published